# example netlify.toml
[build]
  # command = "next build"
  base='client'
  functions = "functions"
  publish = ".next"
# [dev]
#   publish=".next"
  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
# [[redirects]]
  # from = "/api/pusher/auth"
  # to = "/.netlify/functions/:splat"
  # status = 200
  # from = "/api/identity-login"
  # to = "/.netlify/functions/:splat"
  # status = 200

#[[plugins]]
 # package = "netlify-plugin-cloudinary"

  #[plugins.inputs]
  #cloudName = "boar-images"

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
